### ISSUE TITLE
How to construct files under the `ever-vm/src/tests` directory

### ISSUE THREAD

**Issue by Taolaw** [everx-labs/ever-vm#288]
As the title suggests, I want to compile the files under the `ever-vm/src/tests` directory to understand some implementations of TVM. However, I couldn't find the `Cargo.toml` file in the tests directory, and the upper-level `Cargo.toml` file also doesn't compile the contents of this directory. This has left me confused.

**Comment by bvscd** [comment]
These are unit tests that do not require any additional manifest file.
Just run ```cargo test``` command
